version: 1 # version of the lyra config file
projects:
  - path: . # relative path to project in repo
    messages:
      format: ts
      path: src # relative path of messages folder relative from the above project path
    translations:
      path: src/locale # relative path of translations folder relative from the above project path
    languages: # list of language codes supported in the project
      - da
      - de
      - en
      - nl
      - nn
      - sv
