import { getRequestConfig } from 'next-intl/server';
import { promises as fs } from 'fs';
import path from 'path';

import { routing } from './routing';

export default getRequestConfig(async ({ requestLocale }) => {
  let locale = await requestLocale;

  if (!locale || !routing.locales.includes(locale as typeof routing.locales[number])) {
    locale = routing.defaultLocale;
  }

  // Load messages from compiled JSON (generated by scripts/generate-locale-json.ts)
  const filePath = path.join(process.cwd(), 'src', 'locale', 'compiled', `${locale}.json`);
  const fileContents = await fs.readFile(filePath, 'utf8');
  const messages = JSON.parse(fileContents);

  return {
    locale,
    messages,
  };
});
