export enum BLOCK_TYPES {
  BUTTON = 'button',
  HEADER = 'header',
  LIBRARY_IMAGE = 'libraryImage',
  PARAGRAPH = 'paragraph',
}

export enum BlockProblem {
  INVALID_BUTTON_URL = 'INVALID_BUTTON_URL',
  DEFAULT_BUTTON_TEXT = 'DEFAULT_BUTTON_TEXT',
  INVALID_LINK_URL = 'INVALID_LINK_URL',
}

export enum DeliveryProblem {
  EMPTY = 'EMPTY',
  CONTENT_ERROR = 'CONTENT_ERROR',
  NO_SUBJECT = 'NO_SUBJECT',
  NOT_TARGETED = 'NOT_TARGETED',
  TARGETS_NOT_LOCKED = 'TARGETS_NOT_LOCKED',
}
