export const defaultButtonAttributes = {
  backgroundColor: 'black',
  border: 'none',
  borderBottom: 'none',
  borderLeft: 'none',
  borderRadius: 0,
  borderRight: 'none',
  borderTop: 'none',
  color: 'white',
  fontFamily: 'sans-serif',
  fontSize: 16,
  fontStyle: 'normal',
  fontWeight: 'normal',
  height: 50,
  letterSpacing: 'normal',
  lineHeight: '1.15',
  margin: 0,
  marginBottom: 0,
  marginLeft: 0,
  marginRight: 0,
  marginTop: 0,
  padding: 2,
  textAlign: 'center',
  textDecoration: 'none',
  textTransform: 'none',
  width: null,
};

export const defaultImageAttributes = {
  border: 'none',
  borderBottom: 'none',
  borderLeft: 'none',
  borderRadius: 0,
  borderRight: 'none',
  borderTop: 'none',
  margin: 0,
  marginBottom: 0,
  marginLeft: 0,
  marginRight: 0,
  marginTop: 0,
};
