import ClientContext from 'core/env/ClientContext';

export const metadata = {
  description: 'Generated by Next.js',
  title: 'Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ClientContext>{children}</ClientContext>
      </body>
    </html>
  );
}
