import ClientContext from 'core/env/ClientContext';
import { getBrowserLanguage } from 'utils/locale';
import { headers } from 'next/headers';

export const metadata = {
  description: 'Generated by Next.js',
  title: 'Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const lang = getBrowserLanguage(headers().get('accept-language') || '');
  return (
    <html lang="en">
      <body>
        <ClientContext lang={lang}>{children}</ClientContext>
      </body>
    </html>
  );
}
